Phase 03
Star-Academy/Summer1400-FE-Team7 pull request #4
Opened 2021-07-31 14:37 UTC by ParsaArvanehPA

hame oon file haye .js baraye style element ha hastan

2021-07-31 15:18 UTC, BijanEisapour requested changes

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +$--lg-bg-14: #e35a01;
<p dir='rtl' align='right'>
از hsl استفاده کنید که با خودنش بشه تشخیص داد چه رنگیه

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +  background: linear-gradient($deg, $--lg-bg-14 0 7.5%, $--lg-bg-13 7.5% 15%, $--lg-bg-12 15% 22.5%, $--lg-bg-11 22.5% 30%);
<p dir='rtl' align='right'>
به نظر میرسه این چندجا تکرار شده. از متغیر استفاده کنید

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +}
<p dir='rtl' align='right'>
این چهارتا میتونن به یه دونه تبدیل شن. پارامتر ورودی بگیرید

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +    width: 450px;
<p dir='rtl' align='right'>
پیکسل؟

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +    // }
.

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +  }
<p dir='rtl' align='right'>
خب اینا که خیلی شبیه همن. چه نیازی به چهار تا کلاسه؟

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +  direction: ltr !important;
😐

2021-07-31 15:18 UTC, BijanEisapour commented on pages/auth/style.scss
> +  direction: ltr !important;
<p dir='rtl' align='right'>
اولاً از direction استفاده نکنید؛ به جاش تو تگ html از dir استفاده کنید
<br>
ثانیاً قالب سایت شما rtl ئه، پس این چیه؟

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +    if (m.classList.contains("menu-selected")) {
<p dir='rtl' align='right'>
نیاز به این if نیست

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +      m.classList.add("menu-selected");
<p dir='rtl' align='right'>
چه کاریه؟ حذف میکنید بعد دوباره میذارید؟

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +        songList.classList.add("list-compact-view");
😐

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +  songList.classList.toggle("side-menu-opended");
<p dir='rtl' align='right'>
اسم کلاس‌ها و به طور کلی stringها رو همینجوری تو کد رها نکنید. به ازای هر کدوم اول کد یه const تعریف کنید که مشخص باشه چی به چیه

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +});
<p dir='rtl' align='right'>
خیلی شبیه همه. یا تبدیل به یه دونه متد شه یا از یه متد دیگه استفاده کنید و مشترک‌ها رو بذارید توش

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +    volumeBtnImg.src = "../../assets/images/controls/mute.svg";
<p dir='rtl' align='right'>
واسه هر کدوم از آدرس‌ها اول کد یه const بسازید

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +});
<p dir='rtl' align='right'>
برای ریسپانسیو از JS استفاده نکنید. خودِ css به اندازۀ کافی بهتون آپشن میده

2021-07-31 15:18 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +const dblClickHandler = (elem) => {
<p dir='rtl' align='right'>
دابل کلیک رو چی؟ اسم متد گویا نیست

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/index.html
> +        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه</p>
<p dir='rtl' align='right'>
این فقط واسه زمانیه که سایت در مراحل ابتداییش یا واسه مشتری باشه. الان که واسه خودتونه یه متن خوب بذارید

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/style.scss
> +$--box-shadow-width--header: 4px;
<p dir='rtl' align='right'>
تمام متغیرهای global رو داخل یه فایل بذارید که بعداً بتونید راحت تغییرشون بدید

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/style.scss
> +@mixin body-lg-bg {
<p dir='rtl' align='right'>
اگه فقط اینجا استفاده شده اسمش باید با _ شروع شه در غیر این صورت ببریدش تو یه فایل جدا

2021-07-31 15:18 UTC, BijanEisapour commented on styles/main.scss
> +  ///woof bezar
.

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/style.scss
> +body {
<p dir='rtl' align='right'>
این اگه فایل اصلیه، پس چرا واسه auth یه چیز جدا گذاشتید کلاً؟

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/style.scss
> +    & :is(a, p) {
```scss
a, p {
```

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/style.scss
> +    & > img {
<p dir='rtl' align='right'>
نیاز نیس همه جا & بذارید که

2021-07-31 15:18 UTC, BijanEisapour commented on pages/landing/style.scss
> +      li {
<p dir='rtl' align='right'>
اینجاها & نذاشتید درسته

2021-07-31 15:18 UTC, BijanEisapour commented on styles/main.scss
> +}
.

2021-07-31 15:18 UTC, BijanEisapour commented on styles/main.scss
> +  text-align: right;
<p dir='rtl' align='right'>
اگه سایت RTL ئه نیاز به این کار نیس

2021-07-31 15:18 UTC, BijanEisapour commented on styles/main.scss
> +}
<p dir='rtl' align='right'>
به هیچ وجه توصیه نمیشه

2021-07-31 15:18 UTC, BijanEisapour commented on styles/main.scss
> +  user-select: none;
<p dir='rtl' align='right'>
یعنی چی؟ چرا؟ پاکش کنید

2021-07-31 15:18 UTC, BijanEisapour commented on styles/main.scss
> +  height: 100vh;
<p dir='rtl' align='right'>
نیاز به width نیست کلاً پاکش کنید
<br>
در مورد height هم یعنی دقیقِ دقیق همیشه 100vh ئه؟ اگه بیشتر شد چی؟ بهتره از min-height استفاده کنید

2021-08-01 15:31 UTC, BijanEisapour approved these changes

2021-08-01 19:19 UTC, heidarzade-mh approved these changes
![image](https://user-images.githubusercontent.com/79692434/127782842-4862ebf1-0718-4122-851e-3a90b63a616f.png)
سلام خیلی عالی بود. فقط این دکمه منوها میره تو عکسا که بهتر یکم فاصله بذارید

2021-08-02 06:45 UTC, ParsaArvanehPA commented
> ![image](https://user-images.githubusercontent.com/79692434/127782842-4862ebf1-0718-4122-851e-3a90b63a616f.png)
> سلام خیلی عالی بود. فقط این دکمه منوها میره تو عکسا که بهتر یکم فاصله بذارید

اینو رو هم درست کردیم. ممنون که گفتید

2021-08-02 06:46 UTC, ParsaArvanehPA commented
[FIN] phase-03

2021-08-02 06:51 UTC, merged