Phase 04
Star-Academy/Summer1400-FE-Team7 pull request #5
Opened 2021-08-03 18:55 UTC by ParsaArvanehPA

2021-08-03 20:47 UTC, BijanEisapour requested changes
<p dir='rtl' align='right'>
یه سری از فایل‌ها کلاً خالی بودن. اونا رو پاک کنید

2021-08-03 20:47 UTC, BijanEisapour commented on pages/auth/index.html
> +            <input type="text" id="login-email-input" required />
<p dir='rtl' align='right'>
چرا تایپش ایمیل نیست؟

2021-08-03 20:47 UTC, BijanEisapour commented on pages/auth/index.html
> +            <input type="text" id="signup-email-input" required />
<p dir='rtl' align='right'>
ایضاً

2021-08-03 20:47 UTC, BijanEisapour commented on pages/auth/index.html
>            </div>
<p dir='rtl' align='right'>
تکرارش به چه درد میخوره؟ یه بار وارد کرده دیگه

2021-08-03 20:47 UTC, BijanEisapour commented on pages/auth/style.js
> +
.

2021-08-03 20:47 UTC, BijanEisapour commented on pages/auth/style.scss
> +    padding: 0rem 1rem;
<p dir='rtl' align='right'>
واسه صفر نیاز به واحد نیست

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/musicControllers.js
> +  console.log("🚀 resume");
<p dir='rtl' align='right'>
اینا رو پاک کنید
کلاً console log اضافی نداشته باشید

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/musicControllers.js
> +  }
<p dir='rtl' align='right'>
دو تا از caseها یه مقدار دارن بنابراین میتونن باهمدیگه ادغام شن
<br>
اگه حالت default ندارید خب اصن ننویسیدش

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/musicControllers.js
> +  if (evtobj.keyCode == 39 && evtobj.ctrlKey) {
<p dir='rtl' align='right'>
keyCode منسوخ شده به جاش از key استفاده کنید

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

بعدش میتونید کامنت‌ها رو هم پاک کنید چون خودِ key واضحه چیه

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/musicControllers.js
> +        break;
.

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/musicControllers.js
> +};
<p dir='rtl' align='right'>
یکم فاصله بدید بین قسمت‌های مختلف کد

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/placeholders.js
> +    `;
<p dir='rtl' align='right'>
از html template استفاده کنید 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/placeholders.js
> +  const count = 13;
!

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/search.js
> +    // const searchResult
-_-

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/song.js
> +};
<p dir='rtl' align='right'>
یعنی چی؟ از کلید انگلیسی استفاده کنید

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/song.js
> +    songWrapperDiv.className = "song-wrapper";
<p dir='rtl' align='right'>
مشابه این تیکه خیلی زیاد تکرار شده. یه تابع واسش بنویسید

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/song.js
> +    songList.appendChild(songWrapperDiv);
<p dir='rtl' align='right'>
واقعاً متوجه نمیشم چرا اینو اینجوری زدید
<br>
خیلی راحت از html template استفاده کنید

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +// const MENU_SELECTED = "menu-selected";
😠

2021-08-03 20:47 UTC, BijanEisapour commented on pages/dashboard/styles.js
> +  // });
😡

2021-08-03 20:47 UTC, BijanEisapour commented on source/auth/login.js
> +};
<p dir='rtl' align='right'>
وقتی خودِ مرورگر این کارو انجام میده، چرا خودتون‌و اذیت میکنید؟

2021-08-03 20:47 UTC, BijanEisapour commented on source/auth/login.js
> +    console.log("password cant be empty");
<p dir='rtl' align='right'>
این به چه درد میخوره؟ پاک کنید

2021-08-04 08:29 UTC, heidarzade-mh approved these changes

2021-08-04 08:29 UTC, heidarzade-mh commented on pages/auth/style.js
> +//   event.target.setCustomValidity("رمز عبور باید دارای حداقل ۸ کاراکتر،یک حرف و یک عدد باشد");
کامنت‌هارو پاک کنید از وسط کدا.

2021-08-04 08:29 UTC, heidarzade-mh commented on pages/dashboard/song.js
> +};
سعی کنید تعداد خط های هر فایل بیشتر از ۲۰۰ خط نشه

2021-08-04 16:12 UTC, BijanEisapour approved these changes

2021-08-04 18:39 UTC, merged