Phase 06
Star-Academy/Summer1400-FE-Team7 pull request #6
Opened 2021-08-07 09:02 UTC by ParsaArvanehPA

2021-08-07 12:36 UTC, ss53213 commented
سلام 
خیلی عالیه خسته نباشید
چن تا نکته : 
تو صفحه لندینگ وقتی ثبت نام کلیک می کنیم دوباره میره ورود آدرسش اشتباهه احتمالا 
فعلا احتمالا قسمت های مورد علاقه و پلی لیست تکمیل نشده 
وقتی که ما یه آهنگی رو لایک می کنیم بعدش آنلایک ، کلا آهنگه محو میشه 
شاید بهتر باشه یوزر رو فورس کنید که وارد حسابش حتما بشه بعد بتونه موزیک اینا رو پلی یا لایک اینا کنه

2021-08-07 12:37 UTC, ss53213 commented
سلام 
خیلی عالیه خسته نباشید
چن تا نکته : 
تو صفحه لندینگ وقتی ثبت نام کلیک می کنیم دوباره میره ورود آدرسش اشتباهه احتمالا 
فعلا احتمالا قسمت های مورد علاقه و پلی لیست تکمیل نشده 
وقتی که ما یه آهنگی رو لایک می کنیم بعدش آنلایک ، کلا آهنگه محو میشه 
شاید بهتر باشه یوزر رو فورس کنید که وارد حسابش حتما بشه بعد بتونه موزیک اینا رو پلی یا لایک اینا کنه

2021-08-07 12:38 UTC, ss53213 commented
از بخش مورد علاقه من دیگه نمی تونم لینک بشم بخش همه ی آهنگ ها ، نمی دونم چرا

2021-08-07 13:20 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
قسمت navbar وقتی روی ثبت نام میزنی وارد قسمت ورود میشه

2021-08-07 13:23 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
توی قسمت ورود و ثبت نام بنظرم اگه وقتی رو کادرا فوکوس میکنی بوردر کادر یکی از رنگ های سه تا مثلث کناری باشه بهتره چون اینجوری دیگ تنوع رنگ های استفاده شده خیلی زیاد میشه .کلا بنظرم یه خرده رنگ های این قسمتو تغییر بدید و هماهنگ تر کنید بهتره

2021-08-07 13:27 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
قسمت همه آهنگ ها فونت اسم خواننده و اهنگو بزرگتر کنید خیلی ریزه.یه خرده هم از بالا پایین حاشیه بدید فاصله بگیرن

2021-08-07 13:32 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
![aax](https://user-images.githubusercontent.com/67777662/128601932-1101fb8f-5e26-4f60-8966-317a7f859509.PNG)
یه خرده باکس جستجو رو از باکس پایین فاصله بدید بهم چسبیدن کامل.

2021-08-07 13:35 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
قسمت ورود و ثبت نام ، وقتی فوکوس رو از فیلد ها برمیداری label بدون انیمیشن برمیگرده سرجاش که وجهه خوبی نداره

2021-08-07 13:37 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
بنظرم بهتره تو حالت گوشی اون سه تا مستطیل پایین رو بردارید یا کوچیکترشون کنید چون هم چشمو میزنه هم کادر ورود فرو رفته تو مستطیل اول

2021-08-07 13:40 UTC, bolnik commented on assets/images/controls/loading.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
بهتر نیست چون محتوا  فارسیه اسکرول بار سمت راست باشه . بنظرم کللن واسه دیدن اهنگای پایینتر کل صفحه اسکرول نشه بلکه فقط باکس همه اهنگ ها اسکرول شه (سمت راست) . چون اینجوری یه خرده دور از چشمه

2021-08-07 13:54 UTC, bolnik requested changes
نکاتی که گفتم به عنوان کاربری بود که برای اولین بار وارد سایتتون میشه . اگه صلاح دونستید تغییراتو لازمو اعمال کنید

2021-08-07 16:31 UTC, bolnik approved these changes

2021-08-07 17:00 UTC, ss53213 approved these changes

2021-08-08 18:31 UTC, BijanEisapour approved these changes

2021-08-09 08:00 UTC, merged