Phase 09
Star-Academy/Summer1400-FE-Team7 pull request #7
Opened 2021-08-24 14:15 UTC by ParsaArvanehPA

2021-08-24 14:53 UTC, bolnik commented on src/app/pages/auth/login-form/login-form.component.spec.ts
> +  // it('test', async () => {
کامنت اضافی پاک شه

2021-08-24 14:55 UTC, bolnik commented on src/app/pages/dashboard/side-menu/menu-item/make-new-playlist/make-new-playlist.component.spec.ts
> +        let fixture = TestBed.createComponent(MakeNewPlaylistComponent);
این قسمت که توی beforeEach بود چرا دوباره تعریف شده؟

2021-08-24 15:03 UTC, bolnik commented on src/app/pages/dashboard/side-menu/menu-item/menu-item.component.spec.ts
> +    it('should call onRemove', async () => {
اینجا درخواست http فرستاده نشده پس چرا از async استفاده کردید؟

2021-08-24 15:06 UTC, bolnik commented on src/app/pages/dashboard/side-menu/menu-item/make-new-playlist/make-new-playlist.component.ts
> +    //this.uiManager.closeCreatePlaylistPanel();
.

2021-08-24 15:13 UTC, bolnik commented on src/app/pages/dashboard/notification/notification.component.spec.ts
> +    it('should onClose() be called ', async () => {
niazi be async nist . ta jaei ke midunam zamani bayad az async estefade konid ke bekhaid rooye promisi ke method
barmigardone ye amali anajm bedid

2021-08-24 15:14 UTC, bolnik commented on src/app/pages/dashboard/side-menu/side-menu.component.spec.ts
> +    it('should call onLogOutClick', async () => {
.

2021-08-24 15:35 UTC, bolnik requested changes
.

2021-08-24 19:16 UTC, bolnik approved these changes

2021-08-25 01:14 UTC, ss53213 commented
سلام 
من هم همین نکات رو می تونم ذکر کنم
کلا تو بعضی جاها از async و اینا استفاده شده که خب بهتره حذف شن
یا کلا چند جا دیدم که از ورودی و خروجی  برای کامپوننت ها استفاده شده و به نظرم  میشد یکم ساده تر لدون این ها به هدف رسید چون کلا ورودی و خروجی چیز زیاد خوبی از نظر efficiency نیست 
توی بخش pipes هم مثلا بازم می تونست ساده تر باشه 
در کل خیلی عالی بود و خسته نباشید

2021-08-25 01:15 UTC, ss53213 approved these changes

2021-08-25 06:13 UTC, heidarzade-mh approved these changes
خسته نباشید بچه ها

2021-08-25 13:48 UTC, BijanEisapour requested changes

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/floating-label.directive.spec.ts
> +const _FULL_LABEL = 'full-label';
<div dir='rtl' align='right'>
آندرلاین اول چی میگه؟ از طرفی صرفاً با خوندنِ اسم متغیر باید فهمید کارش چیه؛ به جای اینکه بیاید فقط SNAKE_CASE کنید، در موردش توضیح بنویسید

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/like-hover.directive.spec.ts
> +    template: `<img class="fav-icon" appLikeHover [src]="'../../../../assets/images/like.svg'" alt="" />`,
<div dir='rtl' align='right'>
از اونجایی که الان رو انگولار کد میزنید و دیگه مشکی github pages رخ نمیده، آدرس‌ها رو relative ندین

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/floating-label.directive.ts
> +}
<div dir='rtl' align='right'>
این چرا directive ئه؟

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/floating-label.directive.ts
> +}
<div dir='rtl' align='right'>
خط 15 تا 23 چه طرز شرط نوشتنه؟

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/like-hover.directive.ts
> +}
😐

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/show-password.directive.ts
> +const _IMG_URL = {
<div dir='rtl' align='right'>
نذارید از اینا

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/show-password.directive.ts
> +    unShow: '../../assets/images/unshow-password.svg',
hide 😑

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/show-password.directive.ts
> +}
<div dir='rtl' align='right'>
این چرا directive ئه؟

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/directives/show-password.directive.ts
> +}
<p dir='rtl' align='right'>
همچنین متد خط 18 داره کار show و hide رو باهم انجام میده بنابراین اسمش باید تغییر کنه مثلاً ...

`togglePasswordVisibility`

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/models/playlist.ts
> +}
```typescript
import {Song} from './song';

export class Playlist {
    constructor(public name: string, public id: number, public songs: Song[]) { }
}
```

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/models/song.ts
> +}
```typescript
export class Song {
    constructor(
        public id: number = -1,
        public name: string = '',
        public artist: string = '',
        public duration: number = 0,
        public cover: string = '',
        public isFavourite: boolean = false,
        public lyrics: string = '',
        public file: string = '',
        public isSelected: boolean = false
    ) { }
}
```

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/auth.component.html
> +        <app-signup-form *ngIf="!isLoginPage" (onAlreadyHaveAccount)="pageNavigation('signup')"></app-signup-form>
<div dir='rtl' align='right'>
همیشه ngif رو اول بذارید

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/login-form/login-form.component.spec.ts
> +    ];
<div dir='rtl' align='right'>
اینا رو تو فایل جداگانه بذارید، یا حداقل ببریدش خارج از describe

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/login-form/login-form.component.ts
> +    };
<div dir='rtl' align='right'>
بهترین کار اینه که کلاً پیغام‌ها رو بذارید تو یه سرویس یا کلاس جدا ولی اگه حال ندارید حداقل static و readonlyش کنید

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/login-form/login-form.component.ts
> +    };
<div dir='rtl' align='right'>
اون underline مسخره رو هم بردارید😒

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/login-form/login-form.component.ts
> +    //
😠

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/login-form/login-form.component.ts
> +    };
<div dir='rtl' align='right'>
فیلدها رو نزدیک هم بذارید

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/login-form/login-form.component.ts
> +    ngOnInit = (): void => {};
<div dir='rtl' align='right'>
پاک

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/auth/signup-form/signup-form.component.html
> +        <label for="signup-email-input"> ایمیل </label>
<div dir='rtl' align='right'>
بهتره spaceهای اطراف رو پاک کنید

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/dashboard.component.scss
> +// }
😡

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/dashboard.component.scss
> +    padding: 1rem !important;
<div dir='rtl' align='right'>
99 درصد مواقعی که از important استفاده میکنید یعنی کدتون مشکل داره

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/dashboard.component.scss
> +    color: whitesmoke;
<div dir='rtl' align='right'>
کلاً از اینا استفاده نکنید، به همون hsl بچسبید. اگه یه color system تعریف کنید که چه بهتر

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/dashboard.component.scss
> +            height: calc(100vh - #{'max(12vh, 102px)'});
<div dir='rtl' align='right'>
قشنگ مشخصه این کد کثیفه

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/lyrics/lyrics.component.scss
> +    .lyric-wrapper {
<div dir='rtl' align='right'>
چه نیازی به host ئه ؟

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/lyrics/lyrics.component.scss
> +}
<div dir='rtl' align='right'>
خیلی مشکل داره

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.html
> +                "
<div dir='rtl' align='right'>
جای این کد تو ts ئه نه html

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.html
> +                alt="play pause button"
<div dir='rtl' align='right'>
توضیحات باید یه جوری باشه که طرف قشنگ بفهمه قضیه چیه. از طرفی این باید رو button باشه نه img

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.ts
> +                break;
<div dir='rtl' align='right'>
واسه دیفالت break میذارید؟

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/mobile/mobile.component.ts
> +    ngOnInit(): void {}
<div dir='rtl' align='right'>
پاک

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/notification/notification.component.scss
> +    min-width: 420px;
<div dir='rtl' align='right'>
پیکسل؟

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/dashboard/song-list/layout-manager/layout-manager.component.scss
> +            }
<div dir='rtl' align='right'>
من نمیفهمم چرا از پیکسل استفاده میکنید

2021-08-25 13:48 UTC, BijanEisapour commented on src/app/pages/landing/header/header.component.html
> +    <img src="../../../../assets/images/logo.svg" alt="" width="24" height="24" />
width?! height?!

2021-08-26 08:46 UTC, milar7 commented on src/app/directives/floating-label.directive.ts
> +}
درسته میشه اینو با سی اس اس هندل کرد ولی چون در پروژه قبلی با جاوا اسکریپت هندل کرده بودیم گفتیم اینجا هم همین کارو کنیم تا یه تمرینی هم واسه کاستوم دایرکتیو شده باشه ولی خب اگه صلاح نمیدونید مشکلی نیست حذفش می کنم. .در ضمن شرط رو درست کردم

2021-08-26 08:48 UTC, milar7 commented on src/app/directives/like-hover.directive.ts
> +}
اینم به همون دلیل قبلی دایرکتیو کردیم

2021-08-26 09:07 UTC, milar7 commented on src/app/pages/auth/login-form/login-form.component.ts
> +    };
یه کلاس ساختم

2021-08-26 09:09 UTC, milar7 commented on src/app/pages/auth/login-form/login-form.component.ts
> +    };
ببخشید منظورتو متوجه نشدم؟

2021-08-26 09:23 UTC, milar7 commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.ts
> +                break;
https://stackoverflow.com/questions/26138994/should-we-break-the-default-case-in-switch-statement
هر چی شما بگی ولی طبق این بعد دیفالت نیازی نیست بریک بزاری و بزاری شکل بهتری داره و موارد دیگه. راستش من جایی ندیده بودم نزارن و به همین خواطر بوده. اگه مشکلی ایجاد میکنه لطفا بگید که یاد بگیریم

2021-08-26 09:31 UTC, milar7 commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.html
> +                "
بردمش داخل تی اس ولی خب چون لاجیک زیادی داره اینو میگی یا دلیل دیگه ای داره؟ من فکر کردم اگه کارهایی از این قبیل که فقط جنبه ظاهری دارن بهتره همون داخل اچ تی ام ال هندل بشه

2021-08-26 09:53 UTC, milar7 commented on src/app/pages/dashboard/dashboard.component.scss
> +    padding: 1rem !important;
این قطعه کد واسه گزینه حذف از پلی لیست واسه پروژه قبلی بود که ما اینجا کلا عوضش کردیم ولی فراموش کردیم کد سی اس اس رو هم پاک کنیم. خیلی ببخشید

2021-08-26 10:27 UTC, BijanEisapour approved these changes

2021-08-26 10:30 UTC, BijanEisapour commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.ts
> +                break;
<div dir='rtl' align='right'>
شکلی واسه اجرا ایجاد نمیکنه ولی هم نیاز نیس هم منطقی نیس. مثه اینه که من بیام دو تا semicolon آخر هم خط بذارم. مشکل نداره ولی چرا؟
<br>
جالب اینجاس برعکس شما، من هیچوقت ندیدم یه برنامه نویس حرفه ای واسه default اینو بذاره. اصن فلسفۀ دیفالت اینه که ادامۀ کد اجرا نشه، خب اصن کد ادامه نداره که. چی اجرا نشه؟

2021-08-26 10:36 UTC, BijanEisapour commented on src/app/pages/dashboard/mobile/mobile-bottom-navigation/mobile-bottom-navigation.component.ts
> +                break;
<p dir='rtl' align='right'>
اون لینکی که گذاشتی رو هم خوندم. جوابی که انتخاب شده، یا اشتباه ترجمه کرده یا متوجه منظور نویسنده نشده. اون داره میگه واسه آخرین case بهتره break بذاری که خب راست هم میگه، منم این کارو انجام میدم. علتش اینه که بعداً اگه خواستی یه case دیگه اضافه کنی، اون break از قبل هست. واسه code review و git و gtihub هم موثره. دقیقاً مثل گذاشتن ویرگول واسه آخرین آیتم آرایۀ چند خطی.

```js
switch (this.status) {
    case this.playController.statusTypes.STOPPED:
        this.playController.play();
        break;
    case this.playController.statusTypes.PLAYING:
        this.playController.pause();
        break;
    case this.playController.statusTypes.PAUSED:
        this.playController.resume();
        break;
}

const numbers = [
  4,
  8,
  15,
  16,
  23,
  42,
]
```

2021-08-26 11:04 UTC, merged